repos:
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.2
    hooks:
      - id: prettier
        args: ['--write', '--parser', 'html']
        files: \.html$
      - id: prettier
        args: ['--write', '--parser', 'css']
        files: \.css$
